owner: wojtek45000
repo: ha-check

sites:
  - name: Home Assistant CW Fibre
    url: http://cw-fibre.duckdns.org:8123/

status-website:
  baseUrl: /ha-check        # IMPORTANT
  name: Home Assistant Status
  favicon: https://raw.githubusercontent.com/upptime/upptime/master/assets/favicon.png
  logoUrl: https://raw.githubusercontent.com/upptime/upptime/master/assets/logo.png

assignees:
  - wojtek45000

notifications:
  - type: email
    to: wjamka45@gmail.com
