owner: TON_GITHUB_USERNAME
repo: upptime

sites:
  - name: Home Assistant CW Fibre
    url: http://cw-fibre.duckdns.org:8123/

status-website:
  cname: status.TONDOMAINE.com
  favicon: https://raw.githubusercontent.com/upptime/upptime/master/assets/favicon.png
  logoUrl: https://raw.githubusercontent.com/upptime/upptime/master/assets/logo.png

assignees:
  - TON_GITHUB_USERNAME

notifications:
  - type: email
    to: wjamka45@gmail.com
